name: car_wash_dashboard
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  asuka: ^2.2.1
  uicons: ^1.0.1
  dio: ^5.4.3+1
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.20.0
  firebase_remote_config: ^4.3.8
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.1.6
  
  # Moudlar and MobX
  flutter_modular: ^5.0.3
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  google_fonts: ^6.2.1
  validatorless: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  flutter_lints: ^3.0.0
  mobx_codegen: ^2.6.1

flutter:

  uses-material-design: true

  assets:
    - assets/logo/logo.png
    - assets/images/homer.png